name: quickdcp-deploy
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: SBOM
        run: |
          pip install syft
          syft . -o spdx-json > vault/sbom.spdx.json

      - name: Build
        run: docker build -t quickdcp:latest -f infra/Dockerfile .

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy -c infra/fly.toml --remote-only
